const { OPERATIONS, PRIVILEGE_RESOURCES, RESOURCES } = require('../utils/constant/privilege-constant');

const STATIC_ROLES = Object.freeze({
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
});

const STATIC_MODULE_ROLE = Object.freeze({
  [STATIC_ROLES.SUPER_ADMIN]: [RESOURCES.ROLE_MANAGEMENT, RESOURCES.USER_MANAGEMENT],
  [STATIC_ROLES.ADMIN]: [RESOURCES.ROLE_MANAGEMENT, RESOURCES.USER_MANAGEMENT],
});

const SUPER_ADMIN_RESOURCE_OPERATIONS = {
  [PRIVILEGE_RESOURCES.PROFESSION]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.LANGUAGE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.TRIVIA_TYPE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.SOCIAL_LINK]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.GENRE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.SECTION_TYPE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.SECTION_TEMPLATE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],

  [PRIVILEGE_RESOURCES.CELEBRITY_BASIC_INFO]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_PROFESSION_SECTIONS]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_DYNAMIC_SECTIONS]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_CUSTOM_SECTIONS]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_TIMELINE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_TRIVIA]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_RELATED_PERSONALITIES]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_REFERENCES]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
};

const ADMIN_RESOURCE_OPERATIONS = {
  [PRIVILEGE_RESOURCES.PROFESSION]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.LANGUAGE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.TRIVIA_TYPE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.SOCIAL_LINK]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.GENRE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.SECTION_TYPE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [PRIVILEGE_RESOURCES.SECTION_TEMPLATE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],

  [PRIVILEGE_RESOURCES.CELEBRITY_BASIC_INFO]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_PROFESSION_SECTIONS]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_DYNAMIC_SECTIONS]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_CUSTOM_SECTIONS]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_TIMELINE]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_TRIVIA]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_RELATED_PERSONALITIES]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [PRIVILEGE_RESOURCES.CELEBRITY_REFERENCES]: [OPERATIONS.VIEW, OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
};

const STATIC_PRIVILEGES = {
  [STATIC_ROLES.SUPER_ADMIN]: {
    role: STATIC_ROLES.SUPER_ADMIN,
    permissions: Object.entries(SUPER_ADMIN_RESOURCE_OPERATIONS).map(([resource, operations]) => ({
      resource,
      operations,
    })),
    isActive: true,
    isLocked: true,
  },
  [STATIC_ROLES.ADMIN]: {
    role: STATIC_ROLES.ADMIN,
    permissions: Object.entries(ADMIN_RESOURCE_OPERATIONS).map(([resource, operations]) => ({
      resource,
      operations,
    })),
    isActive: true,
    isLocked: true,
  },
};

module.exports = {
  STATIC_ROLES,
  SUPER_ADMIN_RESOURCE_OPERATIONS,
  ADMIN_RESOURCE_OPERATIONS,
  STATIC_PRIVILEGES,
  STATIC_MODULE_ROLE,
};
